name: CI/CD (self-hosted)

on:
  pull_request:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  # test:
  #   runs-on: self-hosted00
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Go tests (dockerized toolchain)---
  #       run: |
  #         docker run --rm \
  #           -v "$PWD/server":/app \
  #           -w /app \
  #           golang:1.19 \
  #           bash -c "echo \$PATH && which go && go version && go mod download && go test -v ./..."

  #     - name: Frontend tests (dockerized toolchain)
  #       run: |
  #         docker run --rm \
  #           -e CI=true \
  #           -v "$PWD/webapp":/app \
  #           -w /app \
  #           node:12.22-bullseye \
  #           bash -lc "npm ci && npm test -- --watch=false"

  build:
    name: Build & Push Docker
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/skmz-backend:latest

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ./webapp
          file: ./webapp/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/skmz-frontend:latest
          
    deploy:
    name: Deploy to Vagrant VM
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy (compose up)
        run: docker compose -f /home/vagrant/skmz/docker-compose.yml up -d --build


    
